// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studentSchema.proto

package protobuf.model;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cc.protobuf.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>string clazz = 3;</code>
   * @return The clazz.
   */
  java.lang.String getClazz();
  /**
   * <code>string clazz = 3;</code>
   * @return The bytes for clazz.
   */
  com.google.protobuf.ByteString
      getClazzBytes();
}
