// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studentSchema.proto

package protobuf.model;

public final class StudentSchema {
  private StudentSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cc_protobuf_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cc_protobuf_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023studentSchema.proto\022\013cc.protobuf\"B\n\007St" +
      "udent\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\r\n\005claz" +
      "z\030\003 \001(\t\022\r\n\005mates\030\004 \003(\tB\022\n\016protobuf.model" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cc_protobuf_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cc_protobuf_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cc_protobuf_Student_descriptor,
        new java.lang.String[] { "Name", "Age", "Clazz", "Mates", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
