// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: studentSchema.proto

package protobuf.model;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cc.protobuf.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>string clazz = 3;</code>
   * @return The clazz.
   */
  java.lang.String getClazz();
  /**
   * <code>string clazz = 3;</code>
   * @return The bytes for clazz.
   */
  com.google.protobuf.ByteString
      getClazzBytes();

  /**
   * <code>repeated string mates = 4;</code>
   * @return A list containing the mates.
   */
  java.util.List<java.lang.String>
      getMatesList();
  /**
   * <code>repeated string mates = 4;</code>
   * @return The count of mates.
   */
  int getMatesCount();
  /**
   * <code>repeated string mates = 4;</code>
   * @param index The index of the element to return.
   * @return The mates at the given index.
   */
  java.lang.String getMates(int index);
  /**
   * <code>repeated string mates = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the mates at the given index.
   */
  com.google.protobuf.ByteString
      getMatesBytes(int index);
}
